### ISSUE TITLE
[QUESTION] Strimzi integration with OPENID (AWS Cognito OAuth)

### ISSUE THREAD

**Issue by klalafaryan** [strimzi/strimzi-kafka-oauth#29]
Hello everyone!

We are trying to integrate the strimzi with AWS cognito OAuth. And seems like strimzi doesn't support integration with JWT. 

It expects to have the scope in the response. I have found following check in OAuthAuthenticator.java
```
        JsonNode scope = result.get("scope");
        if (scope == null) {
            throw new IllegalStateException("Invalid response from authorization server: no scope");
        }
```

We have following configuration in the strimzi kafka:

```
listeners: # Listeners configure how clients connect to the Kafka cluster
      plain: {} # 9092
      tls: {} # 9093
      external:
        type: loadbalancer
        tls: false
        authentication: # not yet tested
          type: oauth
          accessTokenIsJwt: true
          disableTlsHostnameVerification: true
          validIssuerUri: "{validIssuerUri}"
          jwksEndpointUri: "{jwksEndpointUri}"
          clientId: client_id
          clientSecret:
            secretName: oauth-client-secret
            key: secret
        overrides: # to be checked as the hostname doesn't seem to be applied
          bootstrap:
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-bootstrap.int.test.io.
            address: kafka-bootstrap.int.test.io
```

and following configuration for the client:

```
System.setProperty(ClientConfig.OAUTH_TOKEN_ENDPOINT_URI, "https://kafka.auth.test.io/oauth2/token");
System.setProperty(ClientConfig.OAUTH_CLIENT_ID, "client-id");
System.setProperty(ClientConfig.OAUTH_CLIENT_SECRET, "client-secret");
properties.put("sasl.jaas.config", "org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;");
properties.put("security.protocol", "SASL_PLAINTEXT");
properties.put("sasl.mechanism", "OAUTHBEARER");
properties.put("sasl.login.callback.handler.class", "io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler");
```

Could you please give some directions ? 

Any help is appreciated.

Thanks!

**Comment by mstruk** [comment]
@klalafaryan Could you paste a full stacktrace? It seems that your issue is on the client side, not on the Strimzi side.

To get more logging, enable io.strimzi DEBUG level logging.

For the broker specify the following in your Strimzi Kafka custom resource:
```
spec:
  kafka:
    logging:
      type: inline
      loggers:
        log4j.logger.io.strimzi: "DEBUG"
```
