### ISSUE TITLE
Kafka Oauth Configuration - Question

### ISSUE THREAD

**Issue by vperi1730** [strimzi/strimzi-kafka-oauth#67]
Hi Team,

I am trying to launch the kafka cluster with Oauth as auth type with the below configuration.

```
#Kafka/Zookeeper CR
kafkaYaml: |-
  apiVersion: kafka.strimzi.io/v1beta1
  kind: Kafka
  metadata:
    name: kafka-oauth-cluster
  spec:
    clusterCa:
      generateCertificateAuthority: true
    clientsCa:
      generateCertificateAuthority: true
    kafka:
      version: 2.4.0
      replicas: 3
      listeners:
        plain: {}
        tls:
          authentication:
            type: oauth
            clientId: kafka-broker
            clientSecret:
              key: secret
              secretName: broker-oauth-secret
            validIssuerUri: https://<<myip-address>>:8443/auth/realms/master
            jwksEndpointUri: https://<<myip-address>>:8443/auth/realms/master/protocol/openid-connect/certs
            userNameClaim: preferred_username
            tlsTrustedCertificates:
            - secretName: ca-truststore
              certificate: ca.crt
      logging:
        type: inline
       loggers:
         kafka.root.logger.level: "INFO"
      config:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1
        log.message.format.version: "2.4"
      storage:
        type: jbod
        volumes:
        - id: 0
          type: persistent-claim
          size: 20Gi
          deleteClaim: false
    zookeeper:
      replicas: 3
      logging:
        type: inline
        loggers:
          zookeeper.root.logger: "INFO"   
      storage:
        type: persistent-claim
        size: 20Gi
        deleteClaim: false
    entityOperator:
      topicOperator: {}
      userOperator: {}
```

However not sure on the parameter userNameClaim, What should this be populated with, will it be a Kafkauser or something else?

Need help.

**Comment by mstruk** [comment]
Ii you are using Keycloak then it should literally be `preferred_username`. That's the name of the claim (JSON attribute name) inside the JWT token.

**Comment by vperi1730** [comment]
OK sounds good. I am getting an error while deploying the Kafka CR.

```
tls:
          authentication:
            type: oauth
            clientId: kafka-broker
            clientSecret:
              key: secret
              secretName: broker-oauth-secret
            validIssuerUri: https://34.86.144.106:8443/auth/realms/master
            jwksEndpointUri: https://34.86.144.106:8443/auth/realms/master/protocol/openid-connect/certs
            userNameClaim: preferred_username
            tlsTrustedCertificates:
            - secretName: ca-truststore
              certificate: ca.crt(This is line 29, i have taken care of the spaces part)
```

```
Applying kafka.yaml in Kafka-OAuth namespace
error: error parsing /operator/kafka.yaml: error converting YAML to JSON: YAML: line 29: did not find expected key

```

Any clue?

**Comment by mstruk** [comment]
Might be an indentation issue since it complains about the key, not the
value.

**Comment by vperi1730** [comment]
I have actually followed the strimzi blog with all the necessary steps in place. However, I am not able to launch the Kafka cluster.

1) The following are the 2 secrets.
```
k8soptr@jumpbox:~$ kubectl get secrets -n Kafka-oauth
NAME                                                TYPE                                  DATA   AGE
broker-OAuth-secret                                 Opaque                                1      3h43m
ca-truststore                                       Opaque                                1      3h43m

```

2) I have created Kafka-broker, Kafka-producer, and Kafka-consumer on the Keycloak as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/63441996/87875147-c4d54f00-c9ec-11ea-8a61-d8a5eb2dc155.png)

3) Triggered the Kafka cluster with the following configuration.

```
#Kafka/Zookeeper CR
kafkaYaml: |-
  apiVersion: kafka.strimzi.io/v1beta1
  kind: Kafka
  metadata:
    name: kafka-oauth-cluster
  spec:
    clusterCa:
      generateCertificateAuthority: true
    clientsCa:
      generateCertificateAuthority: true
    kafka:
      version: 2.4.0
      replicas: 3
      listeners:
        plain: {}
        tls:
          authentication:
            type: oauth
            clientId: kafka-broker
            clientSecret:
              key: secret
              secretName: broker-oauth-secret
            validIssuerUri: "https://34.86.144.106:8443/auth/realms/master"
            jwksEndpointUri: "https://34.86.144.106:8443/auth/realms/master/protocol/openid-connect/certs"
            userNameClaim: preferred_username
            tlsTrustedCertificates:
            - secretName: ca-truststore
              certificate: ca.crt
       logging:
        type: inline
       loggers:
         kafka.root.logger.level: "INFO"
      config:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1
        log.message.format.version: "2.4"
      storage:
        type: persistent-claim
        size: 20Gi
        deleteClaim: false
    zookeeper:
      replicas: 3
      logging:
        type: inline
        loggers:
          zookeeper.root.logger: "INFO"
      storage:
        type: persistent-claim
        size: 20Gi
        deleteClaim: false
    entityOperator:
      topicOperator: {}
      userOperator: {}
      
```

Following is the error I am receiving for the entire authentication block till certificate: ca.crt. I have checked the indentation, it looks correct.  Need help here to resolve this. 

```
Applying kafka.yaml in kafka-oauth namespace
error: error parsing /operator/kafka.yaml: error converting YAML to JSON: YAML: line 27: did not find expected key

```
